# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(db_index=True, max_length=5)),
                ('locale_path', models.CharField(db_index=True, max_length=256)),
                ('domain', models.CharField(db_index=True, max_length=256)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
