# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosetta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Translation',
            },
            bases=('rosetta.translationbackup',),
        ),
    ]
