language: python
services: memcached

matrix:
  include:
  - python: "3.6"
    env: TOX_ENV=py36-django18
  - python: "3.6"
    env: TOX_ENV=py36-django19
  - python: "3.6"
    env: TOX_ENV=py36-django110
  - python: "3.6"
    env: TOX_ENV=py36-django111
  - python: "2.7"
    env: TOX_ENV=py27-django18
  - python: "2.7"
    env: TOX_ENV=py27-django19
  - python: "2.7"
    env: TOX_ENV=py27-django110
  - python: "2.7"
    env: TOX_ENV=py27-django111

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
