language: python
services: memcached

matrix:
  include:
  - python: "3.6"
    env: TOX_ENV=py36-django111
  - python: "3.6"
    env: TOX_ENV=py36-django20

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
